# Generated by Django 4.1 on 2022-09-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagDis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('media_geral', models.FloatField(verbose_name='Media Geral')),
                ('media', models.FloatField(verbose_name='Media Participantes')),
                ('inscritos', models.IntegerField(verbose_name='Inscritos')),
                ('participates', models.IntegerField(verbose_name='Participantes')),
                ('faltantes', models.IntegerField(verbose_name='Faltantes')),
            ],
        ),
    ]
