# Generated by Django 4.1 on 2022-09-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
       
    ]

