# Generated by Django 4.1 on 2022-09-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220919_2326'),
    ]

    operations = [
    ]
