# Generated by Django 4.1 on 2022-09-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220919_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagdis',
            old_name='participates',
            new_name='participantes',
        ),
        migrations.AddField(
            model_name='tagdis',
            name='data',
            field=models.IntegerField(default=2022, verbose_name='Ano'),
        ),
    ]
