# Generated by Django 4.1 on 2022-09-19 23:43

from django.db import migrations

from app1.models import TagDis

DEFAULT_TAGDIS = (
    ('AC',	325.85,	470.05,	54382,	37699,	16683,	2017),
    ('AL',	351.5, 484.09,	118725,	86206,	32519,	2017)
)


def add_TagDis(apps, schema_editor):
    tagdis = apps.get_model('app1', 'TagDis')

    for uf,media_geral,media,inscritos,participantes,faltantes,data in DEFAULT_TAGDIS:
        tgd = TagDis(
            uf=uf,
            media_geral=media_geral,
            media=media,
            inscritos=inscritos,
            participantes=participantes,
            faltantes=faltantes,
            data=data)
        tgd.save()



def remove_TagDis(apps, schema_editor):
    # This is used to migrate backward
    # You can remove your dog types, or just pass
    # pass

    for uf,media_geral,media,inscritos,participantes,faltantes,data in DEFAULT_TAGDIS:
        tgd = TagDis.objects.get(
            uf=uf,
            media_geral=media_geral,
            media=media,
            inscritos=inscritos,
            participantes=participantes,
            faltantes=faltantes,
            data=data)
        tgd.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_participates_tagdis_participantes_tagdis_data'),
    ]

    operations = [
        migrations.RunPython(add_TagDis,remove_TagDis)
    ]
